name: deploy
on:
  push:
    branches:
      - main
env:
  DATABASE_URL: "postgresql://postgres:lambert@localhost:5432/posts-test-app?schema=public"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: build the project
        run: tsc --build

      - name: produce the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
