name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: build the project
        run: tsc --build

      - name: produce the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: download the artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: create .env
        run: |
          touch .env
          echo "${{secrets.PROD_ENV}}" > .env
